#!/bin/sh
set -e

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications || true
fi

if command -v mandb >/dev/null 2>&1; then
    mandb -q || true
fi

exit 0
